name: pytorch_menpo
channels:
  - menpo
  - pytorch
  - soumith
  - defaults
dependencies:
  - appdirs=1.4.3=py35h28b3542_0
  - asn1crypto=0.24.0=py35_0
  - attrs=18.1.0=py35_0
  - automat=0.7.0=py35_0
  - backcall=0.1.0=py35_0
  - backports=1.0=py35_1
  - backports.shutil_get_terminal_size=1.0.0=py35_2
  - blas=1.0=mkl
  - bleach=2.1.4=py35_0
  - bzip2=1.0.6=h14c3975_5
  - ca-certificates=2018.03.07=0
  - certifi=2018.8.24=py35_1
  - cffi=1.11.5=py35he75722e_1
  - configobj=5.0.6=py35_0
  - constantly=15.1.0=py35h28b3542_0
  - cryptography=2.3.1=py35hc365091_0
  - cycler=0.10.0=py35hc4d5149_0
  - decorator=4.3.0=py35_0
  - docopt=0.6.2=py35_0
  - entrypoints=0.2.3=py35_2
  - fontconfig=2.11.1=6
  - freetype=2.5.5=2
  - get_terminal_size=1.0.0=haa9412d_0
  - gmp=6.1.2=h6c8ec71_1
  - hdf5=1.10.2=hba1933b_1
  - html5lib=1.0.1=py35_0
  - hyperlink=18.0.0=py35_0
  - icu=58.2=h9c2bf20_1
  - idna=2.7=py35_0
  - incremental=17.5.0=py35_0
  - intel-openmp=2018.0.3=0
  - ipykernel=4.8.2=py35_0
  - ipython=4.2.0=py35_0
  - ipython_genutils=0.2.0=py35hc9e07d0_0
  - ipywidgets=4.1.1=py35_0
  - jedi=0.12.1=py35_0
  - jinja2=2.10=py35_0
  - jpeg=9b=h024ee3a_2
  - jsonschema=2.6.0=py35h4395190_0
  - jupyter=1.0.0=py35_4
  - jupyter_client=5.2.3=py35_0
  - jupyter_console=5.2.0=py35h4044a63_1
  - jupyter_core=4.4.0=py35_0
  - libedit=3.1.20170329=h6b74fdf_2
  - libffi=3.2.1=hd88cf55_4
  - libgcc-ng=8.2.0=hdf63c60_1
  - libgfortran-ng=7.3.0=hdf63c60_0
  - libpng=1.6.34=hb9fc6fc_0
  - libsodium=1.0.16=h1bed415_0
  - libstdcxx-ng=8.2.0=hdf63c60_1
  - libtiff=4.0.9=he85c1e1_2
  - libxml2=2.9.8=h26e45fe_1
  - markupsafe=1.0=py35h14c3975_1
  - matplotlib=1.5.1=np111py35_0
  - mistune=0.8.3=py35h14c3975_1
  - mkl=2018.0.3=1
  - mock=2.0.0=py35h70ca42c_0
  - nbconvert=5.3.1=py35_0
  - nbformat=4.4.0=py35h12e6e07_0
  - ncurses=6.1=hf484d3e_0
  - nose=1.3.7=py35_2
  - notebook=5.6.0=py35_0
  - numpy=1.11.3=py35h1d66e8a_10
  - numpy-base=1.11.3=py35h81de0dd_10
  - olefile=0.45.1=py35_0
  - openssl=1.0.2p=h14c3975_0
  - pandas=0.23.4=py35h04863e7_0
  - pandoc=2.2.3.2=0
  - pandocfilters=1.4.2=py35_1
  - parso=0.3.1=py35_0
  - pbr=4.2.0=py35_0
  - pexpect=4.6.0=py35_0
  - pickleshare=0.7.4=py35hd57304d_0
  - pillow=4.2.1=py35_0
  - pip=10.0.1=py35_0
  - prometheus_client=0.3.1=py35h28b3542_0
  - prompt_toolkit=1.0.15=py35hc09de7a_0
  - ptyprocess=0.6.0=py35_0
  - pyasn1=0.4.4=py35h28b3542_0
  - pyasn1-modules=0.2.2=py35_0
  - pycparser=2.18=py35_1
  - pygments=2.2.0=py35h0f41973_0
  - pyopenssl=18.0.0=py35_0
  - pyparsing=2.2.0=py35_1
  - pyqt=4.11.4=py35_4
  - python=3.5.6=hc3d631a_0
  - python-dateutil=2.7.3=py35_0
  - pytz=2018.5=py35_0
  - pyzmq=17.1.2=py35h14c3975_0
  - qt=4.8.7=3
  - qtconsole=4.3.1=py35h4626a06_0
  - readline=7.0=h7b6447c_5
  - scikit-learn=0.19.1=py35hbf1f462_0
  - scipy=0.19.1=py35ha8f041b_3
  - send2trash=1.5.0=py35_0
  - service_identity=17.0.0=py35h28b3542_0
  - setuptools=40.2.0=py35_0
  - simplegeneric=0.8.1=py35_2
  - sip=4.18=py35_0
  - six=1.11.0=py35_1
  - sqlite=3.24.0=h84994c4_0
  - system=5.8=2
  - terminado=0.8.1=py35_1
  - testpath=0.3.1=py35had42eaf_0
  - tk=8.6.8=hbc83047_0
  - tornado=5.1=py35h14c3975_0
  - traitlets=4.3.2=py35ha522a97_0
  - twisted=18.7.0=py35h14c3975_1
  - wcwidth=0.1.7=py35hcd08066_0
  - webencodings=0.5.1=py35_1
  - wheel=0.31.1=py35_0
  - widgetsnbextension=3.4.0=py35_0
  - xz=5.2.4=h14c3975_4
  - zeromq=4.2.5=hf484d3e_1
  - zlib=1.2.11=ha838bed_2
  - zope=1.0=py35_0
  - zope.interface=4.5.0=py35h14c3975_0
  - apptools=4.4.0=py35_0
  - boost=1.59.0=py35_0
  - cyffld2=0.2.4=py35_0
  - cypico=0.2.7=py35_0
  - cyrasterize=0.3.2=py35_0
  - cyvlfeat=0.4.6=py35_0
  - dlib=18.18=py35_2
  - envisage=4.5.1=py35_0
  - ffmpeg=2.7.0=0
  - fftw=3.3.4=0
  - glew=2.0.0=0
  - glfw3=3.2.1=0
  - mayavi=4.5.0=py35_0
  - menpo=0.7.7=py35_0
  - menpo3d=0.5.2=py35_0
  - menpocli=0.0.2=py35_0
  - menpodetect=0.4.1=py35_0
  - menpofit=0.4.1=py35_0
  - menpoproject=2.0=py_0
  - menpowidgets=0.2.1=py35_0
  - metis=5.1.0=0
  - opencv3=3.1.0=py35_0
  - pyface=5.1.0=py35_0
  - scikit-sparse=0.3.1=py35_0
  - suitesparse=4.4.1=0
  - traits=4.5.0=py35_0
  - traitsui=5.1.0=py35_0
  - vlfeat=0.9.20=1
  - vtk=7.0.0=py35_0

